# Generated by Django 2.1.7 on 2019-06-27 22:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_isim', models.CharField(max_length=100, verbose_name='Ad-Soyad')),
                ('contact_ulasim', models.CharField(max_length=150, verbose_name='Ulaşım Bilgisi')),
                ('contact_message', models.TextField(verbose_name='İletişim Mesajı')),
                ('contact_tarih', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İletişim Talebi',
                'verbose_name_plural': 'İletişim Talepleri',
                'ordering': ('-contact_tarih',),
            },
        ),
        migrations.CreateModel(
            name='Makaleler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makale_baslik', models.CharField(max_length=150, verbose_name='Makale Başlığı')),
                ('makale_yayintarihi', models.DateField(verbose_name='Makale Yayın Tarihi')),
                ('makale_mesaj', ckeditor.fields.RichTextField()),
                ('makale_slug', models.SlugField(unique=True)),
                ('makale_kategori', models.CharField(choices=[('ticarethukuku', 'Ticaret Hukuku'), ('tazminathukuku', 'Tazminat Hukuku'), ('sozlesmelerhukuku', 'Sözleşmeler Hukuku'), ('mirashukuku', 'Miras Hukuku'), ('ishukuku', 'İş Hukuku'), ('icraiflashukuku', 'İcra-İflas Hukuku'), ('gayrimenkulhukuku', 'Gayrimenkul Hukuku'), ('cezahukuku', 'Ceza Hukuku'), ('ailehukuku', 'Aile Hukuku')], max_length=50, verbose_name='Makale Kategorisi')),
                ('makale_meta_description', models.CharField(max_length=350, verbose_name='Makale Meta Açıklaması(SEO İÇİN)')),
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
                'ordering': ('-makale_yayintarihi',),
            },
        ),
        migrations.CreateModel(
            name='MakaleTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makale_tag_isim', models.CharField(max_length=100, verbose_name='Makale Tag')),
            ],
            options={
                'verbose_name': 'Makale Etiketi',
                'verbose_name_plural': 'Makale Etiketleri',
            },
        ),
        migrations.CreateModel(
            name='Uzmanliklar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzmanlik_baslik', models.CharField(choices=[('ticarethukuku', 'Ticaret Hukuku'), ('tazminathukuku', 'Tazminat Hukuku'), ('sozlesmelerhukuku', 'Sözleşmeler Hukuku'), ('mirashukuku', 'Miras Hukuku'), ('ishukuku', 'İş Hukuku'), ('icraiflashukuku', 'İcra-İflas Hukuku'), ('gayrimenkulhukuku', 'Gayrimenkul Hukuku'), ('cezahukuku', 'Ceza Hukuku'), ('ailehukuku', 'Aile Hukuku')], max_length=100, verbose_name='Uzmanlık Başlığı')),
                ('uzmanlik_mesaj', ckeditor.fields.RichTextField()),
                ('uzmanlik_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='makaleler',
            name='tag',
            field=models.ManyToManyField(to='mainapp.MakaleTags'),
        ),
    ]
