# Generated by Django 2.1.7 on 2019-06-27 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzmanliklar',
            options={'verbose_name': 'Hukuki Uzmanlık', 'verbose_name_plural': 'Hukuki Uzmanlıklar'},
        ),
        migrations.RemoveField(
            model_name='uzmanliklar',
            name='uzmanlik_slug',
        ),
    ]
